FROM node:alpine

ARG FEATURE_SEARCH_ENABLED
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_DEFAULT_REGION
ARG NEXT_PUBLIC_INDEX_NAME
ARG NEXT_PUBLIC_MEDUSA_BACKEND_URL
ARG NEXT_PUBLIC_SEARCH_API_KEY
ARG NEXT_PUBLIC_SEARCH_ENDPOINT
ARG NODE_ENV
ARG REVALIDATE_SECRET

WORKDIR /app

COPY package.json yarn.lock ./

RUN apk add --no-cache yarn && yarn install --frozen-lockfile

COPY . .

ENV NODE_ENV=$NODE_ENV \
    FEATURE_SEARCH_ENABLED=$FEATURE_SEARCH_ENABLED \
    NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL \
    NEXT_PUBLIC_DEFAULT_REGION=$NEXT_PUBLIC_DEFAULT_REGION \
    NEXT_PUBLIC_INDEX_NAME=$NEXT_PUBLIC_INDEX_NAME \
    NEXT_PUBLIC_MEDUSA_BACKEND_URL=$NEXT_PUBLIC_MEDUSA_BACKEND_URL \
    NEXT_PUBLIC_SEARCH_API_KEY=$NEXT_PUBLIC_SEARCH_API_KEY \
    NEXT_PUBLIC_SEARCH_ENDPOINT=$NEXT_PUBLIC_SEARCH_ENDPOINT \
    REVALIDATE_SECRET=$REVALIDATE_SECRET

RUN yarn build

EXPOSE 8000

CMD ["yarn", "start"]`